spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://192.168.65.128:3306/bill?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.65.128
    port: 6379
    database: 0
mybatis-plus:
  type-aliases-package: com.bill.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

